"""create banking fact tables and views

Revision ID: 1b614a6e8961
Revises: ad2adcbb3a50
Create Date: 2026-09-13 00:21:39.519579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b614a6e8961'
down_revision: Union[str, Sequence[str], None] = 'ad2adcbb3a50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_advances_monthly',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('period_month', sa.Date(), nullable=False),
    sa.Column('organization_unit_id', sa.BigInteger(), nullable=False),
    sa.Column('product_type', sa.String(length=10), nullable=False),
    sa.Column('outstanding_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('account_count', sa.BigInteger(), nullable=False),
    sa.Column('target_account_count', sa.BigInteger(), nullable=False),
    sa.Column('sanctioned_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('disbursed_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('overdue_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.CheckConstraint('account_count >= 0 AND target_account_count >= 0', name=op.f('ck_fact_advances_monthly_advance_non_negative_counts')),
    sa.CheckConstraint('disbursed_amount <= sanctioned_amount', name=op.f('ck_fact_advances_monthly_advance_disbursed_within_sanction')),
    sa.CheckConstraint('outstanding_amount >= 0 AND target_amount >= 0 AND sanctioned_amount >= 0 AND disbursed_amount >= 0 AND overdue_amount >= 0', name=op.f('ck_fact_advances_monthly_advance_non_negative_amounts')),
    sa.CheckConstraint('overdue_amount <= outstanding_amount', name=op.f('ck_fact_advances_monthly_advance_overdue_within_outstanding')),
    sa.CheckConstraint("product_type IN ('EL', 'VL', 'PL', 'HL', 'MSME', 'AGRI')", name=op.f('ck_fact_advances_monthly_advance_valid_product')),
    sa.ForeignKeyConstraint(['organization_unit_id'], ['organization_units.id'], name=op.f('fk_fact_advances_monthly_organization_unit_id_organization_units'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fact_advances_monthly')),
    sa.UniqueConstraint('period_month', 'organization_unit_id', 'product_type', name=op.f('uq_fact_advances_monthly_period_month'))
    )
    op.create_index('ix_fact_advances_org_period', 'fact_advances_monthly', ['organization_unit_id', 'period_month'], unique=False)
    op.create_index('ix_fact_advances_product_period', 'fact_advances_monthly', ['product_type', 'period_month'], unique=False)
    op.create_table('fact_asset_quality_monthly',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('period_month', sa.Date(), nullable=False),
    sa.Column('organization_unit_id', sa.BigInteger(), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('outstanding_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('account_count', sa.BigInteger(), nullable=False),
    sa.Column('slippage_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('recovery_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('target_recovery_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.CheckConstraint('account_count >= 0', name=op.f('ck_fact_asset_quality_monthly_asset_quality_non_negative_accounts')),
    sa.CheckConstraint('outstanding_amount >= 0 AND slippage_amount >= 0 AND recovery_amount >= 0 AND target_recovery_amount >= 0', name=op.f('ck_fact_asset_quality_monthly_asset_quality_non_negative_amounts')),
    sa.CheckConstraint('recovery_amount <= outstanding_amount', name=op.f('ck_fact_asset_quality_monthly_asset_quality_recovery_within_outstanding')),
    sa.CheckConstraint("classification IN ('SMA0', 'SMA1', 'SMA2', 'SUBSTANDARD', 'DOUBTFUL', 'LOSS')", name=op.f('ck_fact_asset_quality_monthly_asset_quality_valid_class')),
    sa.ForeignKeyConstraint(['organization_unit_id'], ['organization_units.id'], name=op.f('fk_fact_asset_quality_monthly_organization_unit_id_organization_units'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fact_asset_quality_monthly')),
    sa.UniqueConstraint('period_month', 'organization_unit_id', 'classification', name=op.f('uq_fact_asset_quality_monthly_period_month'))
    )
    op.create_index('ix_fact_asset_quality_class_period', 'fact_asset_quality_monthly', ['classification', 'period_month'], unique=False)
    op.create_index('ix_fact_asset_quality_org_period', 'fact_asset_quality_monthly', ['organization_unit_id', 'period_month'], unique=False)
    op.create_table('fact_deposits_monthly',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('period_month', sa.Date(), nullable=False),
    sa.Column('organization_unit_id', sa.BigInteger(), nullable=False),
    sa.Column('product_type', sa.String(length=10), nullable=False),
    sa.Column('business_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('account_count', sa.BigInteger(), nullable=False),
    sa.Column('target_account_count', sa.BigInteger(), nullable=False),
    sa.Column('new_accounts', sa.BigInteger(), nullable=False),
    sa.Column('closed_accounts', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('account_count >= 0 AND target_account_count >= 0 AND new_accounts >= 0 AND closed_accounts >= 0', name=op.f('ck_fact_deposits_monthly_deposit_non_negative_counts')),
    sa.CheckConstraint('business_amount >= 0 AND target_amount >= 0', name=op.f('ck_fact_deposits_monthly_deposit_non_negative_amounts')),
    sa.CheckConstraint("product_type IN ('CA', 'SA')", name=op.f('ck_fact_deposits_monthly_deposit_valid_product')),
    sa.ForeignKeyConstraint(['organization_unit_id'], ['organization_units.id'], name=op.f('fk_fact_deposits_monthly_organization_unit_id_organization_units'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fact_deposits_monthly')),
    sa.UniqueConstraint('period_month', 'organization_unit_id', 'product_type', name=op.f('uq_fact_deposits_monthly_period_month'))
    )
    op.create_index('ix_fact_deposits_org_period', 'fact_deposits_monthly', ['organization_unit_id', 'period_month'], unique=False)
    op.create_index('ix_fact_deposits_product_period', 'fact_deposits_monthly', ['product_type', 'period_month'], unique=False)
    op.create_table('fact_digital_products_monthly',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('period_month', sa.Date(), nullable=False),
    sa.Column('organization_unit_id', sa.BigInteger(), nullable=False),
    sa.Column('product_type', sa.String(length=30), nullable=False),
    sa.Column('eligible_customer_count', sa.BigInteger(), nullable=False),
    sa.Column('registered_customer_count', sa.BigInteger(), nullable=False),
    sa.Column('active_customer_count', sa.BigInteger(), nullable=False),
    sa.Column('transaction_count', sa.BigInteger(), nullable=False),
    sa.Column('transaction_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('target_registered_count', sa.BigInteger(), nullable=False),
    sa.Column('target_transaction_count', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('active_customer_count <= registered_customer_count AND registered_customer_count <= eligible_customer_count', name=op.f('ck_fact_digital_products_monthly_digital_customer_funnel')),
    sa.CheckConstraint('eligible_customer_count >= 0 AND registered_customer_count >= 0 AND active_customer_count >= 0 AND transaction_count >= 0 AND target_registered_count >= 0 AND target_transaction_count >= 0', name=op.f('ck_fact_digital_products_monthly_digital_non_negative_counts')),
    sa.CheckConstraint('transaction_amount >= 0', name=op.f('ck_fact_digital_products_monthly_digital_non_negative_amount')),
    sa.CheckConstraint("product_type IN ('MOBILE_BANKING', 'INTERNET_BANKING', 'UPI', 'DEBIT_CARD', 'POS', 'QR', 'AEPS')", name=op.f('ck_fact_digital_products_monthly_digital_valid_product')),
    sa.ForeignKeyConstraint(['organization_unit_id'], ['organization_units.id'], name=op.f('fk_fact_digital_products_monthly_organization_unit_id_organization_units'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fact_digital_products_monthly')),
    sa.UniqueConstraint('period_month', 'organization_unit_id', 'product_type', name=op.f('uq_fact_digital_products_monthly_period_month'))
    )
    op.create_index('ix_fact_digital_org_period', 'fact_digital_products_monthly', ['organization_unit_id', 'period_month'], unique=False)
    op.create_index('ix_fact_digital_product_period', 'fact_digital_products_monthly', ['product_type', 'period_month'], unique=False)
    op.execute("""
        CREATE VIEW vw_deposit_monthly_summary AS
        SELECT period_month, organization_unit_id,
               SUM(business_amount) AS actual_amount,
               SUM(target_amount) AS target_amount,
               SUM(business_amount) - SUM(target_amount) AS gap_to_target,
               GREATEST(SUM(target_amount) - SUM(business_amount), 0) AS shortfall,
               ROUND(100 * SUM(business_amount) / NULLIF(SUM(target_amount), 0), 2) AS achievement_percent,
               SUM(account_count) AS account_count,
               SUM(target_account_count) AS target_account_count,
               SUM(new_accounts) AS new_accounts,
               SUM(closed_accounts) AS closed_accounts
        FROM fact_deposits_monthly
        GROUP BY period_month, organization_unit_id
    """)
    op.execute("""
        CREATE VIEW vw_advance_monthly_summary AS
        SELECT period_month, organization_unit_id,
               SUM(outstanding_amount) AS actual_amount,
               SUM(target_amount) AS target_amount,
               SUM(outstanding_amount) - SUM(target_amount) AS gap_to_target,
               GREATEST(SUM(target_amount) - SUM(outstanding_amount), 0) AS shortfall,
               ROUND(100 * SUM(outstanding_amount) / NULLIF(SUM(target_amount), 0), 2) AS achievement_percent,
               SUM(account_count) AS account_count,
               SUM(target_account_count) AS target_account_count,
               SUM(sanctioned_amount) AS sanctioned_amount,
               SUM(disbursed_amount) AS disbursed_amount,
               SUM(overdue_amount) AS overdue_amount
        FROM fact_advances_monthly
        GROUP BY period_month, organization_unit_id
    """)
    op.execute("""
        CREATE VIEW vw_asset_quality_monthly_summary AS
        SELECT period_month, organization_unit_id,
               SUM(outstanding_amount) AS stressed_amount,
               SUM(account_count) AS stressed_account_count,
               SUM(slippage_amount) AS slippage_amount,
               SUM(recovery_amount) AS recovery_amount,
               SUM(target_recovery_amount) AS target_recovery_amount,
               SUM(recovery_amount) - SUM(target_recovery_amount) AS recovery_gap,
               ROUND(100 * SUM(recovery_amount) / NULLIF(SUM(target_recovery_amount), 0), 2) AS recovery_achievement_percent
        FROM fact_asset_quality_monthly
        GROUP BY period_month, organization_unit_id
    """)
    op.execute("""
        CREATE VIEW vw_digital_monthly_summary AS
        SELECT period_month, organization_unit_id,
               SUM(eligible_customer_count) AS eligible_customer_count,
               SUM(registered_customer_count) AS registered_customer_count,
               SUM(active_customer_count) AS active_customer_count,
               SUM(transaction_count) AS transaction_count,
               SUM(transaction_amount) AS transaction_amount,
               SUM(target_registered_count) AS target_registered_count,
               SUM(target_transaction_count) AS target_transaction_count,
               ROUND(100 * SUM(active_customer_count) / NULLIF(SUM(registered_customer_count), 0), 2) AS activation_percent
        FROM fact_digital_products_monthly
        GROUP BY period_month, organization_unit_id
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute('DROP VIEW IF EXISTS vw_digital_monthly_summary')
    op.execute('DROP VIEW IF EXISTS vw_asset_quality_monthly_summary')
    op.execute('DROP VIEW IF EXISTS vw_advance_monthly_summary')
    op.execute('DROP VIEW IF EXISTS vw_deposit_monthly_summary')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fact_digital_product_period', table_name='fact_digital_products_monthly')
    op.drop_index('ix_fact_digital_org_period', table_name='fact_digital_products_monthly')
    op.drop_table('fact_digital_products_monthly')
    op.drop_index('ix_fact_deposits_product_period', table_name='fact_deposits_monthly')
    op.drop_index('ix_fact_deposits_org_period', table_name='fact_deposits_monthly')
    op.drop_table('fact_deposits_monthly')
    op.drop_index('ix_fact_asset_quality_org_period', table_name='fact_asset_quality_monthly')
    op.drop_index('ix_fact_asset_quality_class_period', table_name='fact_asset_quality_monthly')
    op.drop_table('fact_asset_quality_monthly')
    op.drop_index('ix_fact_advances_product_period', table_name='fact_advances_monthly')
    op.drop_index('ix_fact_advances_org_period', table_name='fact_advances_monthly')
    op.drop_table('fact_advances_monthly')
    # ### end Alembic commands ###
