"""create and seed KPI catalog

Revision ID: 3388099bd02f
Revises: 1b614a6e8961
Create Date: 2026-09-13 00:32:12.824342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3388099bd02f'
down_revision: Union[str, Sequence[str], None] = '1b614a6e8961'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi_catalog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('module', sa.String(length=30), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('actual_formula', sa.Text(), nullable=False),
    sa.Column('target_formula', sa.Text(), nullable=True),
    sa.Column('gap_formula', sa.Text(), nullable=True),
    sa.Column('yoy_formula', sa.Text(), nullable=False),
    sa.Column('qoq_formula', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('approved_by', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kpi_catalog')),
    sa.UniqueConstraint('code', name=op.f('uq_kpi_catalog_code'))
    )
    catalog = sa.table(
        'kpi_catalog',
        sa.column('code', sa.String), sa.column('module', sa.String),
        sa.column('display_name', sa.String), sa.column('description', sa.Text),
        sa.column('unit', sa.String), sa.column('actual_formula', sa.Text),
        sa.column('target_formula', sa.Text), sa.column('gap_formula', sa.Text),
        sa.column('yoy_formula', sa.Text), sa.column('qoq_formula', sa.Text),
        sa.column('approved_by', sa.String),
    )
    yoy = '(current period - same period prior year) / same period prior year * 100'
    qoq = '(current period - comparable period 3 months earlier) / comparable period 3 months earlier * 100'
    gap = 'SUM(actual) - SUM(target); shortfall = MAX(SUM(target) - SUM(actual), 0)'
    snapshot = 'SUM(value) for period_end month (point-in-time balance/count)'
    flow = 'SUM(value) from period_start through period_end (period activity)'
    rows = [
        ('DEPOSIT_BUSINESS_AMOUNT', 'DEPOSITS', 'Deposit business', 'CA/SA deposit balance', 'INR', 'SUM(business_amount)', 'SUM(target_amount)', gap),
        ('DEPOSIT_ACCOUNT_COUNT', 'DEPOSITS', 'Deposit accounts', 'Number of CA/SA accounts', 'ACCOUNTS', 'SUM(account_count)', 'SUM(target_account_count)', gap),
        ('DEPOSIT_NEW_ACCOUNTS', 'DEPOSITS', 'New deposit accounts', 'New CA/SA accounts opened', 'ACCOUNTS', 'SUM(new_accounts)', None, None),
        ('ADVANCE_OUTSTANDING_AMOUNT', 'ADVANCES', 'Advance outstanding', 'Outstanding advance portfolio', 'INR', 'SUM(outstanding_amount)', 'SUM(target_amount)', gap),
        ('ADVANCE_ACCOUNT_COUNT', 'ADVANCES', 'Advance accounts', 'Number of advance accounts', 'ACCOUNTS', 'SUM(account_count)', 'SUM(target_account_count)', gap),
        ('ADVANCE_DISBURSEMENT_AMOUNT', 'ADVANCES', 'Advance disbursement', 'Amount disbursed', 'INR', 'SUM(disbursed_amount)', None, None),
        ('ASSET_QUALITY_OUTSTANDING_AMOUNT', 'NPA_SMA', 'NPA/SMA outstanding', 'Outstanding classified portfolio', 'INR', 'SUM(outstanding_amount)', None, None),
        ('ASSET_QUALITY_ACCOUNT_COUNT', 'NPA_SMA', 'NPA/SMA accounts', 'Number of classified accounts', 'ACCOUNTS', 'SUM(account_count)', None, None),
        ('ASSET_QUALITY_RECOVERY_AMOUNT', 'NPA_SMA', 'Recovery amount', 'Recovery against classified accounts', 'INR', 'SUM(recovery_amount)', 'SUM(target_recovery_amount)', gap),
        ('DIGITAL_REGISTERED_CUSTOMERS', 'DIGITAL', 'Registered digital customers', 'Customers registered for digital products', 'CUSTOMERS', 'SUM(registered_customer_count)', 'SUM(target_registered_count)', gap),
        ('DIGITAL_ACTIVE_CUSTOMERS', 'DIGITAL', 'Active digital customers', 'Customers active on digital products', 'CUSTOMERS', 'SUM(active_customer_count)', None, None),
        ('DIGITAL_TRANSACTION_COUNT', 'DIGITAL', 'Digital transactions', 'Number of digital transactions', 'TRANSACTIONS', 'SUM(transaction_count)', 'SUM(target_transaction_count)', gap),
        ('DIGITAL_TRANSACTION_AMOUNT', 'DIGITAL', 'Digital transaction amount', 'Value of digital transactions', 'INR', 'SUM(transaction_amount)', None, None),
    ]
    op.bulk_insert(catalog, [dict(code=code, module=module, display_name=name, description=description,
                                  unit=unit, actual_formula=actual, target_formula=target,
                                  gap_formula=gap_formula, yoy_formula=yoy, qoq_formula=qoq,
                                  approved_by='POC_GOVERNANCE')
                             for code, module, name, description, unit, actual, target, gap_formula in rows])
    op.execute(sa.text("""
        UPDATE kpi_catalog SET actual_formula = :snapshot
        WHERE code IN ('DEPOSIT_BUSINESS_AMOUNT', 'DEPOSIT_ACCOUNT_COUNT',
                       'ADVANCE_OUTSTANDING_AMOUNT', 'ADVANCE_ACCOUNT_COUNT',
                       'ASSET_QUALITY_OUTSTANDING_AMOUNT', 'ASSET_QUALITY_ACCOUNT_COUNT',
                       'DIGITAL_REGISTERED_CUSTOMERS', 'DIGITAL_ACTIVE_CUSTOMERS')
    """).bindparams(snapshot=snapshot))
    op.execute(sa.text("""
        UPDATE kpi_catalog SET actual_formula = :flow
        WHERE code NOT IN ('DEPOSIT_BUSINESS_AMOUNT', 'DEPOSIT_ACCOUNT_COUNT',
                           'ADVANCE_OUTSTANDING_AMOUNT', 'ADVANCE_ACCOUNT_COUNT',
                           'ASSET_QUALITY_OUTSTANDING_AMOUNT', 'ASSET_QUALITY_ACCOUNT_COUNT',
                           'DIGITAL_REGISTERED_CUSTOMERS', 'DIGITAL_ACTIVE_CUSTOMERS')
    """).bindparams(flow=flow))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kpi_catalog')
    # ### end Alembic commands ###
