"""create organization hierarchy tables

Revision ID: 93b4775bb724
Revises: 9754296a20c8
Create Date: 2026-09-12 23:57:39.762300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93b4775bb724'
down_revision: Union[str, Sequence[str], None] = '9754296a20c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_units',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('office_type', sa.Enum('HO', 'CO', 'RO', 'BRANCH', name='office_type', native_enum=False, create_constraint=True, length=10), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(office_type = 'HO' AND parent_id IS NULL) OR (office_type <> 'HO' AND parent_id IS NOT NULL)", name=op.f('ck_organization_units_ho_parent_rule')),
    sa.CheckConstraint('parent_id IS NULL OR parent_id <> id', name=op.f('ck_organization_units_parent_not_self')),
    sa.ForeignKeyConstraint(['parent_id'], ['organization_units.id'], name=op.f('fk_organization_units_parent_id_organization_units'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_units')),
    sa.UniqueConstraint('code', name=op.f('uq_organization_units_code'))
    )
    op.create_index('ix_organization_units_parent_active', 'organization_units', ['parent_id', 'is_active'], unique=False)
    op.create_index('ix_organization_units_type_active', 'organization_units', ['office_type', 'is_active'], unique=False)
    op.create_table('organization_hierarchy',
    sa.Column('ancestor_id', sa.BigInteger(), nullable=False),
    sa.Column('descendant_id', sa.BigInteger(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.CheckConstraint('(depth = 0 AND ancestor_id = descendant_id) OR (depth > 0 AND ancestor_id <> descendant_id)', name=op.f('ck_organization_hierarchy_depth_matches_relationship')),
    sa.CheckConstraint('depth >= 0', name=op.f('ck_organization_hierarchy_non_negative_depth')),
    sa.ForeignKeyConstraint(['ancestor_id'], ['organization_units.id'], name=op.f('fk_organization_hierarchy_ancestor_id_organization_units'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['descendant_id'], ['organization_units.id'], name=op.f('fk_organization_hierarchy_descendant_id_organization_units'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ancestor_id', 'descendant_id', name=op.f('pk_organization_hierarchy'))
    )
    op.create_index('ix_organization_hierarchy_descendant_depth', 'organization_hierarchy', ['descendant_id', 'depth'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_organization_hierarchy_descendant_depth', table_name='organization_hierarchy')
    op.drop_table('organization_hierarchy')
    op.drop_index('ix_organization_units_type_active', table_name='organization_units')
    op.drop_index('ix_organization_units_parent_active', table_name='organization_units')
    op.drop_table('organization_units')
    # ### end Alembic commands ###
