"""add conversation sessions and messages

Revision ID: a9dd3d4f3b1b
Revises: f77f3f484edd
Create Date: 2026-09-13 00:54:45.580972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9dd3d4f3b1b'
down_revision: Union[str, Sequence[str], None] = 'f77f3f484edd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('structured_context', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversation_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_sessions'))
    )
    op.create_index('ix_conversation_sessions_user_updated', 'conversation_sessions', ['user_id', 'updated_at'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('structured_intent', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant')", name=op.f('ck_conversation_messages_conversation_message_valid_role')),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], name=op.f('fk_conversation_messages_session_id_conversation_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversation_messages_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_messages'))
    )
    op.create_index('ix_conversation_messages_session_created', 'conversation_messages', ['session_id', 'created_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conversation_messages_session_created', table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index('ix_conversation_sessions_user_updated', table_name='conversation_sessions')
    op.drop_table('conversation_sessions')
    # ### end Alembic commands ###
